### ISSUE TITLE
Cannot import textual_plotext: DEFAULT_COLORS does not exist.

### ISSUE THREAD

**Issue by PlasmaHH** [Textualize/textual-plotext#15]
Trying the examplem from the readme I get:

```
Traceback (most recent call last):
  File "/home/plasmahh/src/python/./pl.py", line 5, in <module>
    from textual_plotext import PlotextPlot
  File "/home/plasmahh/.venv/dev/lib64/python3.11/site-packages/textual_plotext/__init__.py", line 3, in <module>
    from .plot import Plot, themes
  File "/home/plasmahh/.venv/dev/lib64/python3.11/site-packages/textual_plotext/plot.py", line 21, in <module>
    from textual.app import DEFAULT_COLORS
ImportError: cannot import name 'DEFAULT_COLORS' from 'textual.app' (/home/plasmahh/.venv/dev/lib64/python3.11/site-packages/textual/app.py)
```

It looks like the internals of theming of textual changed... 

Additionally when I re-create that DEFAULT_COLORS like it was in older versions I get some "ScatterApp object has no attribute dark" error, it seems also that the dark/light mode detection has changed.

**Comment by PlasmaHH** [comment]
Alright. Until that is done I will keep my workaround which is like:
```python
textual.app.DEFAULT_COLORS = {  "dark" : textual.design.ColorSystem(....) }
import textual_plotext
```
because I can't require people using my app to install things from git ;)
